kind: pipeline
type: docker
name: mealgeniusApi

trigger:
  branch:
    - master 
    - dev
  event:
    - push

steps:
  - name: build
    image: maven:3.8.4-openjdk-17
    commands:
      - cd mongodb-mealgeniusapi
      - mvn clean package -DskipTests
    secrets: [ QUARKUS_SECRET ]

  - name: deploy
    image: maven:3.8.4-openjdk-17
    commands:
      - cd mongodb-mealgeniusapi
      - mvn quarkus:dev
    depends_on: [build]