kind: pipeline
type: docker
name: mealgeniusApi

trigger:
  branch:
    - master
    - dev
  event:
    - push

steps:
  - name: build
    image: maven:3.8.4-openjdk-17
    commands:
      - cd mongodb-mealgeniusapi
      - mvn clean package -DskipTests

  - name: docker-build
    image: docker
    commands:
      - cd mongodb-mealgeniusapi
      - docker build -f src/main/docker/Dockerfile.jvm -t quarkus/mongodb-mealgeniusapi-jvm .
    depends_on: [build]

  - name: docker-run
    image: docker
    commands:
      - docker run -i --rm -p 8080:8080 quarkus/mongodb-mealgeniusapi-jvm
    depends_on: [docker-build]
